{% set name = "minisom" %}
{% set version = "2.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1fca9cfeef62b221a89930ad3422b7a24a2bd66ae43ef97332e165f5975c09f1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - numpy >=1.16

test:
  imports:
    - minisom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JustGlowing/minisom
  summary: Minimalistic implementation of the Self Organizing Maps (SOM)
  license: MIT
  license_file: LICENSE
  description: |
    MiniSom is a minimalistic and Numpy based implementation of the Self Organizing Maps (SOM)
  doc_url: https://github.com/JustGlowing/minisom/tree/master/examples
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    - AntoineD
    - maclandrol
    - AntoineD

