{% set name = "minisom" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/MiniSom-{{ version }}.tar.gz
  sha256: c0f1411616d7614fbd440a811975c12c7dfc091baea33efb49f5f4eabad7b966

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - numpy >=1.16

test:
  imports:
    - minisom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JustGlowing/minisom
  summary: Minimalistic implementation of the Self Organizing Maps (SOM)
  license: MIT
  license_file: LICENSE
  description: |
    MiniSom is a minimalistic and Numpy based implementation of the Self Organizing Maps (SOM)
  doc_url: https://github.com/JustGlowing/minisom/tree/master/examples
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    - maclandrol

